apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mytomcat.python.fullname" . }}-config
  labels:
{{ include "mytomcat.python.labels" . | indent 4 }}
data:
  config.yaml: |-
  {{- range $key, $val := .Values.pythonConfig }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}