apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mytomcat.python.fullname" . }}-config
  labels:
{{ include "mytomcat.python.labels" . | indent 4 }}
data:
  config.yaml: |-
    pythonConfig:
      firstVariable: firstValue
      springHost: tomcat.java-app.local
      springPort: 30080
      uri: /