apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mytomcat.python.fullname" . }}-config
  labels:
{{ include "mytomcat.python.labels" . | indent 4 }}
data:
  config.yaml: |-
{{ tpl ( .Files.Get "files/config.yaml" ) . | indent 4 }}