apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mytomcat.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "mytomcat.labels" . | indent 4 }}
spec:
  selector:
    matchLabels: {{- include "mytomcat.matchLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "mytomcat.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "mytomcat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /health/index.html
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}