apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytomcat.fullname" . }}
  labels:
{{ include "mytomcat.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "wordpress.matchLabels" . | nindent 4 }}