{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mytomcat.serviceAccountName" . }}
  labels:
{{ include "mytomcat.labels" . | indent 4 }}
{{- end -}}
