apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytomcat.fullname" . }}
  labels:
{{ include "mytomcat.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http))) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: {{ .Values.service.port  }}
  selector: {{- include "mytomcat.matchLabels" . | nindent 4 }}
